### ISSUE TITLE
HMAC Mismatch generateSignature error

### ISSUE THREAD

**Issue by zuamsyah** [haritsfahreza/go-bca#1]
saya coba pakai fungsi accountstatement cuma data tidak muncul, lalu saya debug kemungkinan generateSignature yang tidak sesuai dengan rumus yang di berikan pada bca documentation.

**Comment by zuams** [comment]
![gambar](https://user-images.githubusercontent.com/17510763/78534478-b172ef00-7814-11ea-9ac4-0145c860f588.png)
![gambar](https://user-images.githubusercontent.com/17510763/78534511-bc2d8400-7814-11ea-8a9b-8a6b7636e191.png)

**Comment by zuamsyah** [comment]
Solved dengan assign `AccessTokendan` `CorporateID` sebelum menggunakan fungsi  `GetAccountStatement`
